---
AWSTemplateFormatVersion: '2010-09-09'
Description: '...'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  JenkinsLocation:
    Description: The IP address range that can be used to Jenkins to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      AMI: ami-14c5486b
    us-east-2:
      AMI: ami-922914f7
    us-west-2:
      AMI: ami-e251209a
    us-west-1:
      AMI: ami-25110f45
    eu-west-1:
      AMI: ami-ca0135b3
    eu-west-2:
      AMI: ami-a36f8dc4
    eu-west-3:
      AMI: ami-969c2deb
    eu-central-1:
      AMI: ami-9a91b371
    ap-northeast-1:
      AMI: ami-92df37ed
    ap-northeast-2:
      AMI: ami-863090e8
    ap-northeast-3:
      AMI: ami-83444afe
    ap-southeast-1:
      AMI: ami-de90a5a2
    ap-southeast-2:
      AMI: ami-423bec20
    ap-south-1:
      AMI: ami-76d6f519
    us-east-2:
      AMI: ami-f63b1193
    ca-central-1:
      AMI: ami-338a0a57
    sa-east-1:
      AMI: ami-3885d854
    cn-north-1:
      AMI: ami-cb19c4a6
    cn-northwest-1:
      AMI: ami-3e60745c
Resources:
  headjenkinsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 8080 to Jenkins
        + SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '8080'
        ToPort: '8080'
        CidrIp:
          Ref: JenkinsLocation
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
  headjenkins:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          jenkins_install:
          - install_cfn
          - update_java
          - install_jenkins
        install_cfn:
          files:
            "/etc/cfn/cfn-hup.conf":
              content:
                Fn::Join:
                - ''
                - - "[main]\n"
                  - stack=
                  - Ref: AWS::StackId
                  - "\n"
                  - region=
                  - Ref: AWS::Region
                  - "\n"
              mode: '000400'
              owner: root
              group: root
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content:
                Fn::Join:
                - ''
                - - "[cfn-auto-reloader-hook]\n"
                  - 'triggers=post.update

'
                  - 'path=Resources.headjenkins.Metadata.AWS::CloudFormation::Init

'
                  - 'action=/opt/aws/bin/cfn-init -v '
                  - "         --stack "
                  - Ref: AWS::StackName
                  - "         --resource headjenkins "
                  - "         --configsets jenkins_install "
                  - "         --region "
                  - Ref: AWS::Region
                  - "\n"
              mode: '000400'
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                - "/etc/cfn/cfn-hup.conf"
                - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
          commands:
            010_sysupd:
              command: "sudo yum -y update"
        update_java:
          commands:
            005_install_new_java:
              command: "sudo yum -y install java-1.8.0-openjdk"
            010_remove_old_java:
              command: "sudo yum -y remove java-1.7.0-openjdk"
            020_add_jenkins_repo:
              command: "sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"
            030_import_jenkins_key:
              command: "sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key"
        install_jenkins:
          commands:
            010_install_jenkins_package:
              command: "sudo yum install jenkins -y"
          services:
            sysvinit:
              jenkins:
                enabled: 'true'
                ensureRunning: 'true'
    Properties:
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - AMI
      InstanceType: t2.micro
      SecurityGroups:
      - Ref: headjenkinsSG
      KeyName:
        Ref: KeyName
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource headjenkins '
            - '         --configsets jenkins_install '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
Outputs:
  JenkinsURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - headjenkins
          - PublicDnsName
        - ":8080"
    Description: URL for configuring Jenkins

